export { default as Input } from './Input'
export { default as Button } from './Button'
export { default as SelectInput } from './SelectInput'
export { default as TestimonialCp } from './TestimonialCp'
export { default as FAQCp} from './FAQCp'
